name: cbrdb
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy
  - sympy
  - matplotlib
  - networkx
  - pandas
  - rdkit
  - chempy
  - requests
  - urllib3
  - ase
  - pymatgen
  - pip:
    - chemparse
    - dimorphite_dl
    - drfp
    - mace-torch
    - equilibrator-api